# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_myuser_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_pic',
            field=models.ImageField(blank=True, upload_to='member'),
        ),
    ]
