# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=25),
        ),
    ]
