# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170217_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
